name: Trigger auto deployment for container-app-fqghe2zoaf2tc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-fqghe2zoaf2tc-AutoDeployTrigger-350005ed-3022-4742-a7a2-17f5342e8ba6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPFQGHE2ZOAF2TC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPFQGHE2ZOAF2TC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPFQGHE2ZOAF2TC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPFQGHE2ZOAF2TC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPFQGHE2ZOAF2TC_REGISTRY_PASSWORD }}
          containerAppName: container-app-fqghe2zoaf2tc
          resourceGroup: appspacesragapp9bc1b2fd
          imageToBuild: default/container-app-fqghe2zoaf2tc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


